sudo: false
language: node_js
node_js:
  - 12 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - npm run build:prod # generate static files
deploy:
  provider: pages
  skip-cleanup: true
   github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public